### ISSUE TITLE
Deploy initial webpage

### ISSUE THREAD

**Issue by adityak-21** [adityak-21/breakout-game#1]
### Tasks
- [x] Make a sample webpage using html css js.
- [x] Deploy it using github pages automated CI/CD pipeline.

**Comment by KartiK-R-Soni** [comment]
Completed with basic github pages setup with deafult domain and CI/CD pipeline

### Task
-  [x]  deploy on custom domain related to game
