### ISSUE TITLE
Add unit tests for checking functions in ball.js

### ISSUE THREAD

**Issue by adityak-21** [adityak-21/breakout-game#17]
## Tasks
- [x] Createball works correctly
- [x] setBottom works correcty
- [x] setLeft works correctly
- [x] getBottom works correctly
- [x] getLeft works correctly

**Comment by adityak-21** [comment]
Task completed.
