### ISSUE TITLE
Add html for the paddle, single brick and ball

### ISSUE THREAD

**Issue by KartiK-R-Soni** [adityak-21/breakout-game#2]
### Tasks

- [x] Html , Css for ball
- [x] Html, Css for brick
- [x] Html , Css for paddle

![Screenshot 2024-08-10 205757](https://github.com/user-attachments/assets/03763ac4-b80d-4070-9dbe-1fed7304f66b)

**Comment by adityak-21** [comment]
Created a basic paddle, ball, and brick using HTML and CSS.
### Task
- [x] Reproduce the bricks as shown in the photo.
- [x] Create a boundary for the game in which the game will be played.

**Comment by KartiK-R-Soni** [comment]
Reproduced the bricks
We have to track the brick count in future for level of game
