### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by KartiK-R-Soni** [adityak-21/breakout-game#22]
## Tasks
- [x]  Make a server using express js 
- [x] Connect to mongo db using server
- [x] Make endpoints /api/leaderboard for post
- [x] Make endpoint /lead for get

**Comment by adityak-21** [comment]
Completed.
