### ISSUE TITLE
Integerate the backend with the frontend 

### ISSUE THREAD

**Issue by KartiK-R-Soni** [adityak-21/breakout-game#25]
## Tasks
- [x] Integerate backend with frontend
- [x] Define logic in frontend for get and post request
- [x] Set Cors policy
