### ISSUE TITLE
Mechanics of ball

### ISSUE THREAD

**Issue by KartiK-R-Soni** [adityak-21/breakout-game#3]
# Add mechanics for moving of ball 

### Tasks
Move ball such that
- [x] Ball bounces from boundaries 
- [x] Ball should have a variable changeable for velocity

**Comment by adityak-21** [comment]
Ball is bouncing on the boundaries correctly and a variable is made for velocity change.
## Task
- [ ] Ball should bounce on the paddle and bricks also correctly
- [ ] Bricks must disappear after each collision with the ball

**Comment by adityak-21** [comment]
Ball bouncing of the boundaries correctly.
